name: GitHub CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  MAIN_PYTHON_VERSION: '3.12'
  PACKAGE_NAME: 'toucan-mvp-calculator'
  PACKAGE_NAMESPACE: 'toucan.mvp.calculator'


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  style:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - name: Code style checks
        uses: ansys/actions/code-style@v5
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

  smoke-tests:
    name: Build and Smoke tests
    runs-on: ${{ matrix.os }}
    needs: [ style ]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
      - uses: ansys/actions/build-wheelhouse@v5
        with:
          library-name: ${{ env.PACKAGE_NAME }}
          library-namespace: ${{ env.PACKAGE_NAMESPACE }}
          operating-system: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    needs: [ style ]
    steps:

      - name: Build documentation
        uses: ansys/actions/doc-build@v5
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          sphinxopts: -j 1 -W –-keep-going

  testing:
    name: Run unit tests
    needs: [ smoke-tests ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
      - name: Run unit tests
        uses: ansys/actions/tests-pytest@v5
        with:
          python-version: ${{ matrix.python-version }}

  package:
    name: Package library
    needs: [ testing, docs ]
    runs-on: ubuntu-latest
    steps:
      - name: Build library source and wheel artifacts
        uses: ansys/actions/build-library@v5
        with:
          library-name: ${{ env.PACKAGE_NAME }}
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

  upload_docs:
    name: Upload documentation
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [ package ]
    steps:
      - name: Deploy the latest documentation
        uses: ansys/actions/doc-deploy-dev@v5
        with:
          cname: 'robpasmue.github.io/toucan-tournament'
          token: ${{ secrets.DEPLOY_DOCS_PAT }}
